force-app/main/default/objects/InterestTable__mdt/InterestTable__mdt.object-meta.xml
<CustomObject>
    <label>Tabela de Juros</label>
    <pluralLabel>Tabelas de juros</pluralLabel>
</CustomObject>

force-app/main/default/objects/InterestTable__mdt/fields/Level1Rate__c.field-meta.xml
<CustomField>
    <fullName>Level1Rate__c</fullName>
    <label>Juros Nivel 1</label>
    <precision>4</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InterestTable__mdt/fields/Level2Rate__c.field-meta.xml
<CustomField>
    <fullName>Level2Rate__c</fullName>
    <label>Juros Nivel 2</label>
    <precision>4</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/InterestTable__mdt/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12</fullName>
                <default>true</default>
                <label>12</label>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PricingService.cls
public with sharing class PricingService {
    public static Decimal calculateFinancingTotalValue(Decimal downPayment, Integer months, Decimal proposedPrice) {
        if (proposedPrice == null || proposedPrice <= 0 || downPayment == null || months == null) {
            throw new AuraHandledException('Parâmetros de entrada inválidos para o cálculo.');
        }

        if(downPayment >= proposedPrice) {
            System.debug(proposedPrice.setScale(2));
            return 0.00;
        }

        Decimal totalPrice = proposedPrice - downPayment;
        Decimal proposedPrice60Percent = proposedPrice * 0.60;

        // Custom metadata com valores de juros
        Map<String, InterestTable__mdt> allRates = InterestTable__mdt.getAll();
        InterestTable__mdt interestTable;
        for(InterestTable__mdt rate : allRates.values()) {
            if(rate.Term__c == String.valueOf(months)) {
                interestTable = rate;
                break;
            }
        }

        if(interestTable == null) {
            throw new AuraHandledException('Não foi encontrado nenhuma tabela de juros para financiamento de ' + months + ' meses');
        }

        Decimal interestPerMonth = downPayment >= proposedPrice60Percent 
        ? interestTable.Level2Rate__c / 100 
        : interestTable.Level1Rate__c / 100;
        
        Decimal totalInterest = totalPrice * interestPerMonth * months;
        Decimal finalPrice = totalPrice + totalInterest;

        System.debug(finalPrice.setScale(2));
        return finalPrice.setScale(2);
    }

    public static Decimal calculateDiscount(Decimal proposedPrice, Decimal discount) {
        return proposedPrice - (proposedPrice * (discount / 100));
    }

}